# Generated by Django 3.1.7 on 2021-03-18 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('price', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('excelent', 'Excelente'), ('good', 'Buena'), ('acceptable', 'Aceptable'), ('damaged', 'Deteriorada'), ('impaired', 'Dañada')], max_length=11)),
            ],
        ),
    ]
