# Generated by Django 3.1.7 on 2021-03-19 01:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('comicsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('days', models.PositiveIntegerField()),
                ('client', models.CharField(max_length=80)),
                ('amount', models.FloatField()),
                ('price', models.FloatField()),
                ('rented_at', models.DateField()),
                ('finished_at', models.DateField()),
                ('comic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rents', to='comicsapp.comic')),
            ],
        ),
    ]
