# Generated by Django 3.1.7 on 2021-03-19 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comicsapp', '0004_auto_20210319_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='finished_at',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='rent',
            name='rented_at',
            field=models.DateTimeField(editable=False),
        ),
    ]
