# Generated by Django 3.1.7 on 2021-03-20 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comicsapp', '0005_auto_20210319_1509'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rent',
            new_name='Rental',
        ),
    ]
