# Generated by Django 3.1.7 on 2021-03-21 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comicsapp', '0006_auto_20210320_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='status',
            field=models.CharField(choices=[('excellent', 'Excelente'), ('good', 'Buena'), ('acceptable', 'Aceptable'), ('impaired', 'Deteriorada'), ('damaged', 'Dañada')], max_length=11),
        ),
    ]
