name: "Continuos Integration"

on:
  push:
    paths-ignore:
      - "*.md"
  pull_request:
    paths-ignore:
      - "*.md"

jobs:
  ci:
    runs-on: ubuntu-20.04
    env:
      DJANGO_SETTINGS_MODULE: config.settings.ci
      SECRET_KEY: "testssecret"
      DEBUG: False
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      
      - name: Installing dependencies
        run: pip install -r requirements/ci.txt
      
      - name: Running tests and coverage
        run: make coverage
